# https://docs.travis-ci.com/user/languages/php
language: php
sudo: required

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_29; PHPUNIT=5.7.*; TYPE=coverage; COVERAGE_FILTER="--testsuite semantic-mediawiki-unit"
      php: 7.1
    - env: DB=mysql; MW=REL1_29; PHPUNIT=5.7.*; TYPE=coverage; COVERAGE_FILTER="--testsuite semantic-mediawiki-integration-jsonscript"
      php: 7.1
    - env: DB=mysql; MW=REL1_29; PHPUNIT=5.7.*; TYPE=coverage; COVERAGE_FILTER="--testsuite semantic-mediawiki-integration-import"
      php: 7.1
    - env: DB=mysql; MW=REL1_29; PHPUNIT=5.7.*; TYPE=coverage; COVERAGE_FILTER="--testsuite semantic-mediawiki-integration-others"
      php: 7.1


# Dec 16, 2015 (GCE switch): Travis support wrote (Tomcat + Java):
# bug in the JDK: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7089443.
# The hostname for the precise-gce platform is longer than 64 characters on the
# VM your job is running on
#- sudo hostname "$(hostname | cut -c1-63)"
#- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
#- cat /etc/hosts # optionally check the content *after*

# Aug 12, 2016: (incident:2p40l49r3yxd) Travis support asks to add `sudo sysctl ...`
# After investigation, removed the lines from Dec 16, 2015 as it emptied the hosts file
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
  - cat /etc/hosts # optionally check the content *before*

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-services.sh
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./tests/travis/update-configuration-settings.sh

script:
  - bash ./tests/travis/run-tests.sh

after_script:
  - if [ ls /tmp/stacktrace* 1> /dev/null 2>&1 ] ; then cat /tmp/stacktrace*.log ; fi
  - if [ -f php.log ] ; then cat php.log ; fi
  - if [ -f /tmp/mediawiki-debug.log ] ; then cat /tmp/mediawiki-debug.log ; fi

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
